### ISSUE TITLE
You Pypi page looks weird...

### ISSUE THREAD

**Issue by pombredanne** [svetlyak40wt/python-processor#2]
I could be an ReST issue.... May be you can try restview by @mgedmin ? It helped me fix my faulty long descriptions so they look good on Pypi.

**Comment by svetlyak40wt** [comment]
Cool utulity, thank you! Now read me is fixed: https://pypi.python.org/pypi/processor/0.10.0

BTW, it was broken because a missing indentation in a CHANGELOG.rst :(

**Comment by pombredanne** [comment]
@svetlyak40wt Thanks for the quick fix my Lord!
